### ISSUE TITLE
Track and report max, min, and average values

### ISSUE THREAD

**Issue by disquisitioner** [ericklein/rco2#10]
I think it'd be useful for RCO2 to keep track of maximum, minimum, and average readings over the period of time it's left on and operating.  This should be easy to add.  

When we've implemented the multiple display screens feature we could have one of those screens display min/avg/max for CO2, Temperature and Humidity.  This should be pretty easy to add too.

**Comment by ericklein** [comment]
I have to restore the code that stores individual CO2 samples to implement an improved version the the sparkline (screen). The persistent storage version of that is in AQ and realtime CO2 respositories. Easy to add tempF and humidity to that.

**Comment by disquisitioner** [comment]
Oh, interesting.   I wasn't thinking about keeping track across power off/on cycles, just while the unit was up and running in any particular location for a reasonable (but still modest) period of time.  How long do you typically leave RCO2 powered up and running when you're using it?

**Comment by ericklein** [comment]
I can reuse most of the code for non-persistent storage

**Comment by ericklein** [comment]
Implemented and tested measure.h functionality via screenAggregateData()
