### ISSUE TITLE
Disallow CO2 readings below 400?

### ISSUE THREAD

**Issue by disquisitioner** [ericklein/rco2#9]
I've noticed when moving the SCD40 from one environment to another it is possible to get CO2 readings below 400.  I believe this is because the SCD40 is auto-recalibrating itself by default, so if left in one location long enough it will recalibrate so as have the lowest reading observed during that recalibration period to be 400.  Moving the unit to a new location can result in new readings that are lower than the redefined definition of 400 and so CO2 values below 400 are reported.

Should we prevent that by never displaying a value below 400?  If so, then we should check every sensor reading and clip it to 400 if it is less than 400.

**Comment by ericklein** [comment]
good catch. There is an error handler in sensorCO2Read() that returns false and displays a debugMessage if (sensorData.ambientCO2<400 || sensorData.ambientCO2>6000), but the actual value is still passed through. I'll clip it to 400.

**Comment by disquisitioner** [comment]
Cool.  I think my SCD40 auto-recalibrated after running for several consecutive days as the typical CO2 reading went from 700 - 1000 down to 400 - 700.   I then brought it along on this trip and when I fired it up in the conference hotel it said "397".  I'm still not sure I like the whole auto-recalibration feature but do believe it is enabled by default.   This may be more of an issue for RCO2, though, given its purpose is to be moved around often from location to location rather than sit somewhere long enough for a recalibration interval to pass.

**Comment by ericklein** [comment]
I just saw the first out of range reading error and the code both flags the issue via debugMessage and sets sensorData.ambientCO2 to either the low or high bounds depending on the (errant) value.
